[deps]
CopernicusMarine = "cd43e856-93a3-40c8-bc9e-6146cdce14fa"
ClimaOcean = "0376089a-ecfe-4b0e-a64f-9c555d74d754"
ClimaSeaIce = "6ba0ff68-24e6-4315-936c-2e99227c95a4"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
